export const EVENT_TYPES = [
  "Advocacy Events",
  "Automated Phone Banks",
  "Brainstorm",
  "Canvasses",
  "Carpools",
  "Community Canvases",
  "Community Events",
  "Data Entry Events",
  "Friend-to-Friend Outreaches",
  "Fundraiser Campaigns",
  "Fundraisers",
  "Groups",
  "House Parties",
  "Interest Forms",
  "Letter Writing Events",
  "Literature Drop-Offs",
  "Meet and Greets",
  "Meetings",
  "Office Openings",
  "Other Events",
  "Petitions",
  "Phone Banks",
  "Pledges",
  "Pole Monitoring Events",
  "Postcard Writing Events",
  "Rallies",
  "Signature Gatherings",
  "Social Media Campaigns",
  "Text Banks",
  "Town Halls",
  "Trainings",
  "Visibility Events",
  "Volunteer Shifts",
  "Voter Registration",
  "Watch Parties",
  "Workshops",
] as const;

export const ACCESSIBILITY_FEATURES = [
  "ASL Interpretation",
  "Accessible restrooms",
  "Audio Description for Video",
  "Dedicated Parking Spots",
  "Dedicated Seating",
  "Live Captioning",
  "Mainly Flat Ground",
  "No Stairs or Steps",
  "Spanish Interpretation",
  "Wheelchair Ramp",
  "Wide Entry Doors and Walkways",
] as const;
